name: Go Test

on:
  push:       # 每次 push 代码时运行
  pull_request: # 每次提交 PR 时运行
  workflow_dispatch: # 允许手动触发

jobs:
  test:
    runs-on: ubuntu-latest  # 运行环境（可以改成 macos-latest / windows-latest）
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 拉取代码

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23  # 这里可以改成项目需要的 Go 版本

      - name: Install dependencies
        run: go mod tidy  # 确保依赖正确

      - name: Run specific test in test folder
        run: go test ./test/utils/image/  # 仅运行 test 目录下的测试